### ISSUE TITLE
Add configuration for trimming whitespaces 

### ISSUE THREAD

**Issue by rwillemsandroid** [icapps/combined_barcode_scanner#12]
Camera scans do not trim trailing white spaces, while Zebra lazer scans do. 

Align trimming of whitespaces and add a configuration flag for this.

**Comment by vanlooverenkoen** [comment]
Fixed it in on of our project. A pull request should be created to fix it upstream

**Comment by NicolaVerbeeck** [comment]
Should it? I mean, this is something that can be done easily in client code. Who knows maybe someone needs those witespaces for something

**Comment by vanlooverenkoen** [comment]
@NicolaVerbeeck fair point.

**Comment by ikbendewilliam** [comment]
@NicolaVerbeeck the reason for this is that a keyboard scanner or Zebra scanner does this already, but the camera does not do this. We won't force this (disabled by default), but will improve usability

**Comment by NicolaVerbeeck** [comment]
Sure, let's add it then
